name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: 'Sync source code'
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install Dependencies
        uses: msys2/setup-msys2@v2
        with:
          install: make mingw-w64-x86_64-meson mingw-w64-x86_64-ninja mingw-w64-x86_64-pkg-config  mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2 mingw-w64-x86_64-glew
      - name: Build Hades
        run: |
          meson build -Dstatic_executable=true
          cd build
          ninja
      - name: Test Hades
        run: |
          ./build/Hades.exe --help
      - name: Collect Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hades-win64
          path: build/Hades.exe
          if-no-files-found: error

  mac-os:
    runs-on: macos-latest
    steps:
      - name: 'Sync source code'
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install Dependencies
        run: |
          brew install meson ninja sdl2 glew create-dmg
      - name: Build Hades
        run: |
          rm -rf /tmp/build/
          mkdir -p /tmp/build/Hades.app

          meson --buildtype=release --prefix=/tmp/build/Hades.app --bindir=Contents/MacOS build --werror
          ninja -C build install

          chmod +x /tmp/build/Hades.app/Contents/MacOS/hades /tmp/build/Hades.app/Contents/MacOS/run.sh

          otool -L /tmp/build/Hades.app/Contents/MacOS/hades

          cp /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib /tmp/build/Hades.app/Contents/MacOS/
          install_name_tool -change /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib @executable_path/libSDL2-2.0.0.dylib /tmp/build/Hades.app/Contents/MacOS/hades

          cp /usr/local/opt/glew/lib/libGLEW.2.2.dylib /tmp/build/Hades.app/Contents/MacOS/
          install_name_tool -change /usr/local/opt/glew/lib/libGLEW.2.2.dylib @executable_path/libGLEW.2.2.dylib /tmp/build/Hades.app/Contents/MacOS/hades
      - name: Test Hades
        run: |
          /tmp/build/Hades.app/Contents/MacOS/hades --help
      - name: Pack Hades
        run: |
          rm -rf Hades.dmg

          pwd

          create-dmg \
              --volname "Hades Installer" \
              --volicon ./resource/macos/hades.icns \
              --background ./resource/macos/background.png \
              --window-pos 200 120 \
              --window-size 575 375 \
              --icon-size 100 \
              --icon Hades.app 150 225 \
              --hide-extension Hades.app \
              --app-drop-link 425 225 \
              Hades-Installer.dmg \
              /tmp/build/

      - name: Collect Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hades-macos
          path: Hades-Installer.dmg
          if-no-files-found: error

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: 'Sync source code'
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build libsdl2-dev libglew-dev libgtk-3-dev
      - name: Build Hades
        run: |
          meson build --werror
          cd build
          ninja
      - name: Test Hades
        run: |
          ./build/hades --help
      - name: Collect Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hades-linux
          path: build/hades
          if-no-files-found: error
